[tool.poetry]
name = "pytest-proj"
version = "0.1.0"
description = ""
authors = ["Lysenko Nikita <nike7cr77@ya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
